sighupio/module-policy

- README.md
- docs/releases/v1.0.1.md
- katalog/gatekeeper/rules/constraints/must_have_liveness_probe.yml
- katalog/gatekeeper/rules/constraints/must_have_readiness_probe.yml
- katalog/gatekeeper/rules/constraints/must_have_unique_service_selector.yml
If you change `enforcementaction` to `dryrun` nothing happens, because the correct form is `enforcementAction` with the capital A. This didn't get caught before because `deny` is the default enforcement action for constraints.
> Fixed enforcementAction typo

- README.md
- docs/releases/unreleased.md
- katalog/gatekeeper/core/kustomization.yaml
- katalog/gatekeeper/core/service-monitor.yml
- katalog/gatekeeper/core/svc.yml
Hello team!
This PR adds the metrics port to the service definition and the service monitor definition for prometheus scraping in order to be able to see Gatekeeper metrics on a Grafana Dashboard
> Prometheus Monitoring

- docs/releases/unreleased.md
- katalog/gatekeeper/core/deploy.yml
Hi team!
As discussed, I'm opening this PR to disable the deployment in HA by default. According to upstream this feature is not yet fully supported.
From the README upstream:
> We are currently working on addressing issues that may cause multi-pod deployments of Gatekeeper to not work as expected.
References:
https://github.com/open-policy-agent/gatekeeper#admission-webhook-fail-open-status
https://github.com/open-policy-agent/gatekeeper/issues/671
https://github.com/open-policy-agent/gatekeeper/issues/348
https://github.com/open-policy-agent/gatekeeper/issues?q=is%3Aopen+is%3Aissue+label%3A%22Fail+Closed%22
> Disable High Availability

- docs/releases/unreleased.md
- katalog/gatekeeper/rules/constraints/must_have_liveness_probe.yml
- katalog/gatekeeper/rules/constraints/must_have_readiness_probe.yml
- katalog/gatekeeper/rules/constraints/must_have_security_controls.yml
- katalog/gatekeeper/rules/templates/livenessprobe_template.yml
- katalog/gatekeeper/rules/templates/readinessproble_template.yml
- katalog/gatekeeper/rules/templates/security_controls_template.yml
Ciao team!
While deploying Istio along with the default constraints available in this module, someone can face issues deploying apps into the mesh as they receive a container as a sidecar (aka istio proxy). These sidecars can not be modified so we added a flag in all the constraints to exclude the rule in the sidecar container.
The default behaviour is not affected. If you plan to deploy Istio, make sure to mark the new feature flag as `true`.
Example `K8sLivenessProbe`:
```
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sLivenessProbe
metadata:
name: liveness-probe
spec:
enforcementAction: deny
parameters:
excludeIstio: true # Set this flag to true
```
> FIX: Add exclude istio flag

- README.md
- katalog/gatekeeper/gpm/README.md
- katalog/gatekeeper/gpm/kustomization.yaml
This PR adds Gatekeeper Policy Manager's manifests to the fury-kubernetes-opa module so you can install GPM together in one shot.
> Add GPM manifests to katalog

- katalog/gatekeeper/core/vwh.yml
See https://github.com/open-policy-agent/gatekeeper/issues/870
This commit aligns the vwh to the Gatekeeper upstream, and also fixes the below bug.
We were creating a new K8s 1.18 cluster with Fury 1.5.1 on OCI, using only a single master node.
When we applied all manifests at the same time, gatekeeper got deployed with 5 sec webhook timeout.
We observed that the cluster reached a broken, nonfunctional state -
e.g. no new pods could start, CNI seemed broken, and some core components were crashlooping.
Apiserver was full of errors about API requests timing out.
After a couple days of debugging, we found out that Gatekeeper was the issue.
The linked github issue perfectly fits our case.
Indeed, reducing the vwh timeout from 5 sec to 3 sec "repairs" the cluster quite quickly.
> Reduce gatekeeper webhook timeout for 5s to 3s

- .drone.yml
- README.md
- docs/releases/unreleased.md
- docs/releases/v1.4.0.md
- katalog/gatekeeper/README.md
- katalog/gatekeeper/core/crd.yml
- katalog/gatekeeper/core/deploy.yml
- katalog/gatekeeper/core/kustomization.yaml
- katalog/gatekeeper/core/pdb.yml
- katalog/gatekeeper/rules/README.md
- katalog/gatekeeper/rules/templates/kustomization.yaml
- katalog/tests/gatekeeper.sh
SIGHUP team maintains this module updated and tested. That is the main reason why we worked on this new release.
Minor works have been done in the constraint templates while updating the OPA Gatekeeper package.
Continue reading the [Changelog](#changelog) to discover them:
- Update OPA Gatekeeper version from: 3.2.2 to [3.4.0](https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.4.0)
- Add Pod Disruption Budget
- Kubernetes support:
- Deprecate Kubernetes 1.17 support.
- Kubernetes 1.20 is considered stable.
- Add a missing template *(`unique_service_selector_template`)* to the template package.
- Updated GPM to v0.4.2
To upgrade this core module from `v1.3.1`, you need to download this new version, then apply the
`kustomize` project. No further action is required.
```bash …
```
> Upgrade module 1.4.0

- katalog/gatekeeper/core/deploy.yml
This PR adds a missing temp volume to Gatekeeper's Audit pod. Without this volume the audit is not working, you get this error:
```
{"level":"error","ts":1644408172.8148265,"logger":"controller","msg":"audit manager audit() failed","process":"audit","error":"open /tmp/audit: no such file or directory","stacktrace":"github.com/open-policy-agent/gatekeeper/pkg/audit.(*Manager).auditManagerLoop\n\t/go/src/github.com/open-policy-agent/gatekeeper/pkg/audit/manager.go:561"}
```
policy enforcement when you apply a new object is unaffected by this issue though
> add missing temp volume to gatekeeper-audit

- .drone.yml
- katalog/gatekeeper/gpm/MAINTENANCE.md
- katalog/gatekeeper/gpm/deployment.yaml
- katalog/gatekeeper/gpm/kustomization.yaml
- katalog/gatekeeper/gpm/rbac.yaml
- katalog/gatekeeper/gpm/service.yaml
This PR takes the manifests for the GPM package from upstream and renders them local to fix #21.
Adds also a `MAINTENANCE.md` file with instructions.
> GPM: use local files instead of remote manifests.

- katalog/gatekeeper/core/MAINTENANCE.md
- katalog/gatekeeper/core/deploy.yml
Being that setting this parameter doesn't seem to have downsides nor caused any issues until now, we proceed to set it by default.
This PR also adds a `MAINTENACE.md` for Gatekeeper
> Bugfix: set audit chunksize by default

- docs/releases/unreleased.md
- katalog/gatekeeper/rules/templates/livenessprobe_template.yml
- katalog/gatekeeper/rules/templates/protected_namespace.yml
- katalog/gatekeeper/rules/templates/readinessproble_template.yml
- katalog/gatekeeper/rules/templates/security_controls_template.yml
- katalog/gatekeeper/rules/templates/unique_ingress_template.yml
- katalog/gatekeeper/rules/templates/unique_service_selector_template.yml
Update provided ConstraintTemplates to consider the case that `input.review.operation` is not set when the audit process runs.
Fixes #59
> bugfix: Audit skipped on provided Constraints

- katalog/gatekeeper/core/MAINTENANCE.md
- katalog/gatekeeper/core/deploy.yml
The parameter is not needed anymore, since we updated gatekeeper to v3.8 and --audit-chunk-size is set by default to 500 since v3.7
Fixes #66
> fix: drop audit-chunk-size custom parameter

- README.md
- katalog/gatekeeper/core/MAINTENANCE.md
adds a section about exempting namesapces from the policy enforcement process to the main Readme.
> docs: add namespace exemption instructions

- docs/releases/v1.7.1.md
- katalog/gatekeeper/rules/constraints/patches/all-matches.yml
- katalog/gatekeeper/rules/constraints/patches/deployment-matches.yml
- katalog/gatekeeper/rules/constraints/patches/ingress-matches.yml
- katalog/gatekeeper/rules/constraints/patches/matches.yml
Add to the list of excepted namespaces of the default rules the `tigera-operator` and `calico-system` namespace in use by the Tigera operator introduced in the latest version of the Networking module.
> Add Tigera operator namespaces to the default exceptions

- .bumpversion.cfg
- README.md
- docs/COMPATIBILITY_MATRIX.md
- docs/releases/v1.7.2.md
- katalog/gatekeeper/README.md
- katalog/gatekeeper/core/MAINTENANCE.md
- katalog/gatekeeper/core/kustomization.yaml
- update Gatekeeper to v3.9.2
- prepare for release v1.7.2 of the module
Changes in upstream ([v3.9.1](https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.9.1) and [v3.9.2](https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.9.2))
- They've updated some internal lib and fixed a CVE, with no major changes from 3.9.0 (the version we were including)
- There are no changes to the manifests in upstream
> feat(gatekeeper): update to v3.9.2 and prepare v1.7.2 release

- katalog/gatekeeper/rules/constraints/patches/all-matches.yml
- katalog/gatekeeper/rules/constraints/patches/deployment-matches.yml
- katalog/gatekeeper/rules/constraints/patches/ingress-matches.yml
- katalog/gatekeeper/rules/constraints/patches/matches.yml
Add exemptions to the defaults rules for the new namespaces used by the Tigera Operator and VMware CSI in the recent versions:
- calico-api
- vmware-system-csi
> fix(rules): add exemption for calico apiserver and vmware CSI namespaces

- katalog/gatekeeper/monitoring/alert-rules.yaml
Align the field used to describe the alert with what we are using in the rest of the alerts and in the AlertManager template for the Slack notifications.
> fix(monitoring): fix description field in alertrules

- katalog/gatekeeper/rules/config/config.yml
- katalog/gatekeeper/rules/templates/unique_ingress_template.yml
- delete sync of deprecated APIs for Ingress
- adjust duplicated ingress checks rule
tested E2E test locally and are passing with K8s 1.24.0.
Fixes #87
> fix(rules): delete references to deprecated Ingress API

- .bumpversion.cfg
- .drone.yml
- README.md
- docs/COMPATIBILITY_MATRIX.md
- docs/CONTRIBUTING.md
- docs/releases/v1.1.0.md
- docs/releases/v1.7.3.md
- katalog/gatekeeper/README.md
Add documentation for release v1.7.3
Fixed some old references to the master branch that got renamed to main
> prepare for release v1.7.3

- .drone.yml
deprek8n is not maintained anymore. Switching to Fairwinds Pluto to check for removed Kubernetes API usage in our manifests.
I'm adding check for Kubernetes 1.24.0 and NOT failing when finding APIs that are going to be deprecated in next versions, fail the step only when using APIs that have been removed.
See the run for this PR branch as an example: https://ci.sighup.io/sighupio/fury-kubernetes-opa/563/2/4
> chore(ci): deprecate deprek8n in favor of fairwinds pluto

- katalog/gatekeeper/monitoring/kustomization.yaml
Add annotation to put the module's Grafana dashboards inside the "OPA" folder for better organization.
> feat: put dashboards in "OPA" grafana folder

- .drone.yml
- README.md
- katalog/gatekeeper/core/MAINTENANCE.md
- katalog/gatekeeper/core/crd.yml
- katalog/gatekeeper/core/kustomization.yaml
- katalog/gatekeeper/core/rbac.yml
- katalog/gatekeeper/gpm/kustomization.yaml
- katalog/tests/gatekeeper-manifests/mutation.yaml
- katalog/tests/gatekeeper.sh
- add k8s 1.26 support to CI
- remove k8s 1.22 support from CI
- add triggers for `develop` branch to CI
- update OPA Gatekeeper to v3.12
- update GPM to v1.0.4
- update e2e tests to include mutations
- update docs
> support for Kubernetes 1.26

- README.md
- katalog/gatekeeper/gpm/kustomization.yaml
Bump GPM to v1.0.9 that includes several fixes to OIDC authentication, multicluster view, and updated dependencies.
Fixes https://github.com/sighupio/product-management/issues/283
Related image sync PR:
- https://github.com/sighupio/fury-distribution-container-image-sync/pull/174
> feat: bump GPM to v1.0.9

- katalog/gatekeeper/core/crd.yml
- katalog/gatekeeper/core/kustomization.yaml
- katalog/gatekeeper/core/rbac.yml
- Update GateKeeper image from version 3.12 to 3.14.0
- Update RBAC
- Update CRD: add new feature ExpansionTemplateStatus 
for more detailed information about this release:
https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.14.0
Docs (readme, maintenance manual) will be updated in another task. 
1. deploy manfest. Results Success
2. upgrade from the previous version. Results Success
3. check grafana dashboard. Results Success
summary: no changes are needed to upgrade this module from the previous version. (OPA 1.9.0)
> feat(opa): version bump to 3.14.0

- .drone.yml
- katalog/tests/kind/config.yml
We've implemented KIND (Kubernetes in Docker) for running E2E tests, ensuring compatibility and functionality across Kubernetes versions:
- 1.26.6
- 1.27.3
- 1.28.0
- 1.29.0
Additionally, we've updated the Pluto target version to k8s=v1.29.0 to check for deprecated APIs against this Kubernetes version.
> refactor(ci): use kind for e2e test

- katalog/gatekeeper/README.md
- katalog/gatekeeper/core/MAINTENANCE.md
- katalog/gatekeeper/core/crd.yml
- katalog/gatekeeper/core/deploy.yml
- katalog/gatekeeper/core/kustomization.yaml
- katalog/gatekeeper/core/rbac.yml
- katalog/gatekeeper/monitoring/MAINTENANCE.md
- katalog/gatekeeper/rules/README.md
- katalog/gatekeeper/rules/kustomization.yaml
- katalog/tests/gatekeeper.sh
- katalog/tests/kapp/exists.yaml
Update OPA Gatekeeper core to v3.17.1, adding compatibility with Kubernetes 1.30 and 1.31.
With the update to 3.17 Gatekeeper now allows:
- 🎓 [Integration with Kubernetes Validating Admission Policy (VAP)](https://open-policy-agent.github.io/gatekeeper/website/docs/validating-admission-policy) is now alpha.
- 🎓 CEL-based policies enforced through Gatekeeper is in beta!
- 🎬 Ability to enforce specific action for Gatekeeper webhook, audit, gator, or VAP in the same constraint through scopedEnforcementActions field under spec in Constraints.
The [VAP](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) integration is very interesting, [it is under a feature gate until Kubernetes 1.30 that enables it by …
> feat: update OPA Gatekeeper to v3.17.1

- docs/releases/unreleased.md
- katalog/tests/kapp/exists.yaml
Add a rebaseRule to the manifests used by kapp to avoid the deletion of the `gatekeeper-webhook-server-cert` secret contents on every apply.
This change will make kapp copy the contents if they exist in the cluster instead of applying the empty content from the manifests.
> [!NOTE]
> This change fixes a bug when applying the module with `kapp`, method used by furyctl since KFD v1.31.0.
> This is not a bug of the OPA module itself.
Closes https://github.com/sighupio/fury-distribution/issues/337
Ref: https://carvel.dev/kapp/docs/v0.64.x/config/#rebaserules
See the linked issue for more details.
None.
None
> fix(kapp): don't recreate Gatekeepers TLS secret content on every apply

- .drone.yml
Added dependencies between pipelines to avoid creating 8 Kind clusters simultaneously.
See above.
None.
None.
> fix(ci): add dependencies between pipelines
