README.md, docs/releases/v1.0.2.md, katalog/gatekeeper/core/deploy.yml
Hi
This PR is intended to solve #4 
Thanks!
=> BUGFIX: Disable seccomp

.drone.yml, katalog/tests/helper.bash
Add deprek8ion step in the policeman pipeline.
FIX bash linter on helper library.
=> Add deprek8ion

katalog/gatekeeper/rules/templates/unique_ingress_template.yml, katalog/tests/gatekeeper-manifests/ingress_rejected_duplicated.yml
Resolves https://github.com/sighupio/fury-kubernetes-opa/issues/5
Tested locally and it's passing, we should enable tests on PRs.
=> implemented check for unique id using paths

README.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/gpm/kustomization.yaml
=> Update GPM to v0.4.1

examples/registry-override/README.md, examples/registry-override/gatekeeper/kustomization.yaml, katalog/gatekeeper/core/kustomization.yaml, katalog/gatekeeper/gpm/kustomization.yaml, katalog/gatekeeper/kustomization.yaml, katalog/gatekeeper/monitoring/kustomization.yaml, katalog/gatekeeper/monitoring/service-monitor.yml, katalog/gatekeeper/rules/config/config.yml, katalog/gatekeeper/rules/config/kustomization.yaml, katalog/gatekeeper/rules/constraints/kustomization.yaml, katalog/gatekeeper/rules/constraints/must_have_unique_ingresses.yml, katalog/gatekeeper/rules/kustomization.yaml, katalog/gatekeeper/rules/templates/kustomization.yaml, katalog/gatekeeper/rules/templates/security_controls_template.yml, katalog/gatekeeper/rules/templates/unique_ingress_template.yml, katalog/gatekeeper/rules/templates/unique_service_selector_template.yml, katalog/tests/gatekeeper-manifests/deploy-rejected-without-livenessProbe.yml, katalog/tests/gatekeeper-manifests/deploy_ns_whitelisted.yml, katalog/tests/gatekeeper-manifests/deployment-allowed.yml, katalog/tests/gatekeeper-manifests/deployment_reject_label_latest.yml, katalog/tests/gatekeeper-manifests/deployment_rejected_missing_resources.yml, katalog/tests/gatekeeper-manifests/deployment_trusted.yml, katalog/tests/gatekeeper-manifests/pod-rejected-without-livenessProbe.yml
Following #22 created an example folder with all the possible image override needed (if someone is self hosting on another registry and so on)
=> Example on registry override

README.md, docs/releases/unreleased.md, katalog/gatekeeper/gpm/kustomization.yaml
Hello!
This PR is to update the GPM package to the latest release (v0.4.2)
=> Update GPM to v0.4.2

README.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/gpm/kustomization.yaml
This PR is to update the GPM package to latest version upstream (v0.5.0)
=> Update GPM to v0.5.0

.drone.yml, docs/releases/unreleased.md, katalog/gatekeeper/core/vwh.yml, katalog/gatekeeper/rules/constraints/kustomization.yaml, katalog/gatekeeper/rules/constraints/must_have_namespace_label_to_be_safely_deleted.yml, katalog/gatekeeper/rules/templates/kustomization.yaml, katalog/gatekeeper/rules/templates/livenessprobe_template.yml, katalog/gatekeeper/rules/templates/protected_namespace.yml, katalog/gatekeeper/rules/templates/readinessproble_template.yml, katalog/gatekeeper/rules/templates/security_controls_template.yml, katalog/gatekeeper/rules/templates/unique_ingress_template.yml, katalog/gatekeeper/rules/templates/unique_service_selector_template.yml, katalog/tests/gatekeeper-manifests/ns-can-be-deleted-with-protection-disabled.yml, katalog/tests/gatekeeper-manifests/ns-cannot-be-deleted-without-protection-enabled.yml, katalog/tests/gatekeeper.sh
Hi everyone 👋 , 
as @nandajavarma suggested, I am splitting the PR https://github.com/sighupio/fury-kubernetes-opa/pull/27/commits in 2 because it involves also the introduction of git-chglog that deserves to be in another chapter of the book.
So refer for this to the PR #27
=> Protecting deletion of namespaces

README.md, docs/releases/unreleased.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/gpm/kustomization.yaml
this PR updates GPM to the latest version released upstream (besidestream? xD)
PS to @nandajavarma we still need to sync the image from quay into our registry
=> update Gatekeeper Policy Manager to v0.5.1

README.md, docs/COMPATIBILITY_MATRIX.md, katalog/gatekeeper/README.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/monitoring/README.md, katalog/gatekeeper/rules/README.md
This PR updates the various readmes to the new standard for Fury 1.23. There's some improvement left to do in each package readme, until we decide what to do with them
=> Documentation Update

README.md, docs/releases/unreleased.md, katalog/gatekeeper/core/MAINTENANCE.md, katalog/gatekeeper/core/crd.yml, katalog/gatekeeper/core/deploy.yml, katalog/gatekeeper/core/kustomization.yaml, katalog/gatekeeper/core/mwh.yml, katalog/gatekeeper/core/ns.yml, katalog/gatekeeper/core/pdb.yml, katalog/gatekeeper/core/psp.yml, katalog/gatekeeper/core/rbac.yml, katalog/gatekeeper/core/svc.yml, katalog/gatekeeper/core/vwh.yml
- Updates all the manifests to align them with the latest version from upstream (3.8.1).
- Updated package maintenance documentation.
- Updated Readme for Gatekeeper package
- Added unreleased note
Fixes #52
=> feat: update gatekeeper package to 3.8.1

README.md, docs/releases/unreleased.md, katalog/gatekeeper/README.md, katalog/gatekeeper/gpm/MAINTENANCE.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/gpm/kustomization.yaml
=> feat: update GPM package to v1.0.0

katalog/tests/gatekeeper.sh
Add tests that validate the audit process if working as expected.
The test deploys a pod before all the Gatekeeper stack that will trigger violations after the rules are deployed.
The violations should then appear in the `status` field of the constraints.
A second test checks that after the Gatekeeper stack has been deployed the violations are present.
Fixes #62
=> chore: add audit check to E2E tests

README.md, docs/releases/v1.7.1.md, katalog/gatekeeper/gpm/kustomization.yaml
Update Gatekeeper Policy Manager to v1.0.2
=> feat(gpm): update to v1.0.2

.drone.yml
Fixes https://github.com/sighupio/product-management/issues/284
=> chore(e2e): add 1.27

README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v1.10.0.md, katalog/gatekeeper/README.md, katalog/gatekeeper/core/crd.yml, katalog/gatekeeper/core/kustomization.yaml, katalog/gatekeeper/core/rbac.yml
- Update Maintenace document
- Update Main Readme
- Update Package Readme
- Update Compatibility Matrix 
- Add release notes version 1.10.0
This PR Depends on #100
=> docs(opa): Release 1.10 add compatibility to k8s 1.27

README.md, katalog/gatekeeper/core/MAINTENANCE.md, katalog/gatekeeper/core/crd.yml, katalog/gatekeeper/core/deploy.yml, katalog/gatekeeper/core/kustomization.yaml, katalog/gatekeeper/gpm/deployment.yaml, katalog/gatekeeper/gpm/kustomization.yaml, katalog/gatekeeper/gpm/rbac.yaml, katalog/gatekeeper/gpm/service.yaml
I've updated Gatekeeper to version 3.15.1 and GPM to v1.0.10. Both were tested with Kubernetes versions 1.28 and 1.29 using Kind.
=> Gatekeeper 3.15.1 and GPM v1.0.10 

README.md, katalog/kyverno/core/crds.yaml, katalog/kyverno/core/deploy.yaml, katalog/kyverno/core/kustomization.yaml
This PR introduces the following changes:
- Kyverno Version Bump
- Update Docs for this module
- Kustomize Images newTag
all these components was successfully tested on  1.29 and 1.28 Kubernetes versions in kind clusters
=> feat(kyverno): version bump chart v3.1.4

README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v1.12.0.md
this PR adds the following updates:
- Release Notes for v1.12.0 
- Update Compatibility matrix
- Update the Main readme 
This PR depends on:
- #105 
- #106 
- #107
=> docs(release-1.12.0): Release notes for v1.12.0

README.md, katalog/gatekeeper/gpm/README.md, katalog/gatekeeper/gpm/kustomization.yaml
- Bump Gatekeeper Policy Manager to version 1.0.13.
=> feat(gpm): bump to v1.0.13
